# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

 desc "Build and deploy to appcenter"
 lane :deployToAppCenter do
  
  appcenter_upload(
  api_token: "<appcenter token>",
  owner_name: "<your appcenter account name>",
  app_name: "<your app name>",
  apk: "<path to android build binary>"
)
 
 end
end
